### ISSUE TITLE
Produces errors when trying to merge files with short-form functions

### ISSUE THREAD

**Issue by joffotron** [dakoo/cloudformation-yml-merger-cli#1]
i.e. I get the error:
`failed to merge the cloudformation yaml files YAMLException: unknown tag !<!Ref> at line 21, column 36:
          Name: !Ref InternalDomainName`

when I give it a file that contains:
```yaml
Resources:
  ReferralExchangeDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      AliasTarget:
        DNSName:
          Ref: InternalLoadBalancer
        HostedZoneId: XXXXXXXXXXXXX
      HostedZoneId: XXXXXXXXXXXXX
      Name: !Ref InternalDomainName
```

It does the same for more complex examples, such as:

```yaml
MyNotCondition:
  !Not [!Equals [!Ref EnvironmentType, ""]]
```

Guide:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-not

Is this format of function reference something you will be able to support? Thanks :)
